config/routes.rb
Rails.application.routes.draw do
  get 'get_follows', to: 'follows#getFollows'
  get 'user_search', to: 'follows#userSearch'
  root 'index#home'
  get 'sign_out', to: 'session#destroy'
  get 'auth/:provider/callback', to: 'session#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'sign_in', to: 'session#new'
  post 'log_in', to: 'session#create'
  patch 'users/:id/update_portrait', to: 'users#updatePortrait', as: 'update_portrait'
  patch 'users/:id/update_pwd', to: 'users#updatePassword', as: 'update_pwd'
  get 'profile', to: 'profile#show'
  get 'api/get_events', to: 'api#getEvents', as: 'get_events'
  post 'events/:id/like', to: 'events#like', as: 'like_event'
  post 'events/:id/dislike', to: 'events#dislike', as: 'dislike_event'
  # post 'events/book', to: 'events#book', as: 'book_event'
  # post 'events/cancel', to: 'events#cancel', as: 'cancel_event'
  post 'events/picture/upload/:id', to: 'events#add_img'
  post 'events/picture/delete/:id/:p_id', to: 'events#delete_img'
  get 'get_forum', to: 'posts#getForum', as: 'get_forum'
  resources :users
  resources :events
  resources :posts
  resources :applies, path: :applications, only: [:create, :destroy], as: "edit_apply"
  post 'follows', to: 'follows#create'
  delete 'follows', to: 'follows#destroy'
  post 'applications/:id/approve', to: 'applies#approve', as: 'application_approve'
  post 'applications/:id/disapprove', to: 'applies#disapprove', as: 'application_disapprove'
  get 'get_applications', to: 'applies#getApplications', as: 'get_applications'
  get ':user_id', to: 'index#show', as: 'index'
  get '/events/:id/uploadImg', to:'events#uploadImg'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  include SessionHelper
  skip_before_action :authorized, only: [:googleAuth, :new, :create]
  def googleAuth
    # Get access tokens from the google server
    access_token = request.env["omniauth.auth"]
    user = User.from_omniauth(access_token)
    # Access_token is used to authenticate request made from the rails application to the google server
    user.google_token = access_token.credentials.token
    # Refresh_token to request new access_token
    # Note: Refresh_token is only sent once during the first request
    refresh_token = access_token.credentials.refresh_token
    user.google_refresh_token = refresh_token if refresh_token.present?
    user.save
    log_in(user)
    redirect_to index_path(user.id)
  end

  def destroy
    log_out(@current_user)
    redirect_to root_path
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to index_path(user.id)
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to root_path
      # render 'new'
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
    def log_in user
        session[:current_user_id] = user.id
    end

    def log_out(current_user)
        session.delete(:current_user_id)
        current_user = nil
    end
end

app/views/session/_new.html.erb
<!-- Modal -->
<div class="modal fade" id="log_in_modal" tabindex="-1" role="dialog" aria-labelledby="log_in_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_for(:session, url: log_in_path) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="log_in_label">Sign In/Sign Up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <h2>Sign In</h2>
            <br>
            <div class="form-group row">
              <%= f.label :email, class: "col-sm-3"%>
              <div class="col-sm-9">
                <%= f.email_field :email, class:"form-control" %>
              </div>
            </div>
            <div class="form-group row">
              <%= f.label :password, class: "col-sm-3" %>
              <div class="col-sm-9">
                <%= f.password_field :password, class:"form-control" %>
              </div>
            </div>
            <div class="form-group text-center">
              <%= f.submit "Sign In", class: "btn btn-primary col-sm-6" %>
            </div>
            <div class="text-center">
              <p> New user? <%= link_to "Sign Up now!", new_user_path %></p>
            </div>
            <div class="text-center">
              <%= link_to '/auth/google_oauth2', class:'btn border' do %>
                <%= content_tag(:i, nil, class: "fab fa-lg fa-google text-danger") %>
                <span>Sign in with Google</span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/session/googleAuth.html.erb
<h1>Session#googleAuth</h1>
<p>Find me in app/views/session/googleAuth.html.erb</p>

app/views/session/new.erb
<!-- Modal -->
<div class="modal fade" id="log_in_modal" tabindex="-1" role="dialog" aria-labelledby="log_in_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_for(:session, url: log_in_path) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="log_in_label">Sign In/Sign Up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <h2>Sign In</h2>
            <br>
            <div class="form-group row">
              <%= f.label :email, class: "col-sm-3"%>
              <div class="col-sm-9">
                <%= f.email_field :email, class:"form-control" %>
              </div>
            </div>
            <div class="form-group row">
              <%= f.label :password, class: "col-sm-3" %>
              <div class="col-sm-9">
                <%= f.password_field :password, class:"form-control" %>
              </div>
            </div>
            <div class="form-group text-center">
              <%= f.submit "Sign In", class: "btn btn-primary col-sm-6" %>
            </div>
            <div class="text-center">
              <p> New user? <%= link_to "Sign Up now!", new_user_path %></p>
            </div>
            <div class="text-center">
              <%= link_to '/auth/google_oauth2', class:'btn border' do %>
                <%= content_tag(:i, nil, class: "fab fa-lg fa-google text-danger") %>
                <span>Sign in with Google</span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/session/new.html.erb
<!-- Modal -->
<div class="modal fade" id="log_in_modal" tabindex="-1" role="dialog" aria-labelledby="log_in_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_for(:session, url: log_in_path) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="log_in_label">Sign In/Sign Up</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="container-fluid">
            <h2>Sign In</h2>
            <br>
            <div class="form-group row">
              <%= f.label :email, class: "col-sm-3"%>
              <div class="col-sm-9">
                <%= f.email_field :email, class:"form-control" %>
              </div>
            </div>
            <div class="form-group row">
              <%= f.label :password, class: "col-sm-3" %>
              <div class="col-sm-9">
                <%= f.password_field :password, class:"form-control" %>
              </div>
            </div>
            <div class="form-group text-center">
              <%= f.submit "Sign In", class: "btn btn-primary col-sm-6" %>
            </div>
            <div class="text-center">
              <p> New user? <%= link_to "Sign Up now!", new_user_path %></p>
            </div>
            <div class="text-center">
              <%= link_to '/auth/google_oauth2', class:'btn border' do %>
                <%= content_tag(:i, nil, class: "fab fa-lg fa-google text-danger") %>
                <span>Sign in with Google</span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="modal-footer"></div>
      </div>
    <% end %>
  </div>
</div>

app/views/session/signOut.html.erb
<h1>Session#signOut</h1>
<p>Find me in app/views/session/signOut.html.erb</p>