config/routes.rb
Rails.application.routes.draw do
  get 'get_follows', to: 'follows#getFollows'
  get 'user_search', to: 'follows#userSearch'
  root 'index#home'
  get 'sign_out', to: 'session#destroy'
  get 'auth/:provider/callback', to: 'session#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'sign_in', to: 'session#new'
  post 'log_in', to: 'session#create'
  patch 'users/:id/update_portrait', to: 'users#updatePortrait', as: 'update_portrait'
  patch 'users/:id/update_pwd', to: 'users#updatePassword', as: 'update_pwd'
  get 'profile', to: 'profile#show'
  get 'api/get_events', to: 'api#getEvents', as: 'get_events'
  post 'events/:id/like', to: 'events#like', as: 'like_event'
  post 'events/:id/dislike', to: 'events#dislike', as: 'dislike_event'
  # post 'events/book', to: 'events#book', as: 'book_event'
  # post 'events/cancel', to: 'events#cancel', as: 'cancel_event'
  post 'events/picture/upload/:id', to: 'events#add_img'
  post 'events/picture/delete/:id/:p_id', to: 'events#delete_img'
  get 'get_forum', to: 'posts#getForum', as: 'get_forum'
  resources :users
  resources :events
  resources :posts
  resources :applies, path: :applications, only: [:create, :destroy], as: "edit_apply"
  post 'follows', to: 'follows#create'
  delete 'follows', to: 'follows#destroy'
  post 'applications/:id/approve', to: 'applies#approve', as: 'application_approve'
  post 'applications/:id/disapprove', to: 'applies#disapprove', as: 'application_disapprove'
  get 'get_applications', to: 'applies#getApplications', as: 'get_applications'
  get ':user_id', to: 'index#show', as: 'index'
  get '/events/:id/uploadImg', to:'events#uploadImg'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/index/home.html.erb
<div class="card bg-dark text-white" style="height: 100%; width: 100%; object-fit: contain">
    <%= image_tag("index.jpg", style:"width: 100%; object-fit: contain;") %>
    <div class="card-img-overlay">
        <h3 class="card-title stroke">Please signin or signup</h3>
        <div class="center" style="margin-top: 18%;">
            <b><h1 class="card-text stroke">Welcome to the Events Manager</h1></b>
            <br>
            <h4 class="card-text stroke">A single account to register events all around the world.</h4>
            <h4 class="card-text stroke">What's more - hosting your own events!</h4>
        </div>
    </div>
</div>

app/views/index/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Basic Profile</h3>
      </div>
      <div class="card-body">
        <p class="card-text">
          <%= gravatar_for @user %>
          <%= @user.name %>
        </p>
        <div class="card-text d-flex align-items-center justify-content-end">
          <% if current_user?(@user) %>
            <div>
              <%= link_to  "Edit profile", profile_path %>
            </div>
          <% else %>
            <div class="follow-link">
              <% if current_user.following?(@user) %>
                <%= link_to_unfollow current_user.id, @user.id, "flip" %>
              <% else %>
                <%= link_to_follow current_user.id, @user.id, "flip" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <br>
    <div class="card" id="follows">
      <div class="card-header">
        <h3 class="card-title">Follows</h3>
      </div>
      <div class="card-body">
        <%= render partial: "follows/load_follows" %>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <% if current_user?(@user) %>
      <div class="card" id="applications">
        <div class="card-header">
          <h3 class="card-title">Applications</h3>
        </div>
        <div class="card-body">
          <%= render partial: "applies/load_applications" %>
        </div>
      </div>
    <% end %>
    <br>
    <div class="card" id="events">
      <div class="card-header">
        <h3 class="card-title">Events</h3>
      </div>
      <div class="card-body">
        <%= render_async get_events_path(user_id: @user.id), 'data-turbolinks-track': 'reload' do %>
          <%= load_jpg %>
        <% end %>
      </div>
    </div>
  </div>
</div>