config/routes.rb
Rails.application.routes.draw do
  get 'get_follows', to: 'follows#getFollows'
  get 'user_search', to: 'follows#userSearch'
  root 'index#home'
  get 'sign_out', to: 'session#destroy'
  get 'auth/:provider/callback', to: 'session#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'sign_in', to: 'session#new'
  post 'log_in', to: 'session#create'
  patch 'users/:id/update_portrait', to: 'users#updatePortrait', as: 'update_portrait'
  patch 'users/:id/update_pwd', to: 'users#updatePassword', as: 'update_pwd'
  get 'profile', to: 'profile#show'
  get 'api/get_events', to: 'api#getEvents', as: 'get_events'
  post 'events/:id/like', to: 'events#like', as: 'like_event'
  post 'events/:id/dislike', to: 'events#dislike', as: 'dislike_event'
  # post 'events/book', to: 'events#book', as: 'book_event'
  # post 'events/cancel', to: 'events#cancel', as: 'cancel_event'
  post 'events/picture/upload/:id', to: 'events#add_img'
  post 'events/picture/delete/:id/:p_id', to: 'events#delete_img'
  get 'get_forum', to: 'posts#getForum', as: 'get_forum'
  resources :users
  resources :events
  resources :posts
  resources :applies, path: :applications, only: [:create, :destroy], as: "edit_apply"
  post 'follows', to: 'follows#create'
  delete 'follows', to: 'follows#destroy'
  post 'applications/:id/approve', to: 'applies#approve', as: 'application_approve'
  post 'applications/:id/disapprove', to: 'applies#disapprove', as: 'application_disapprove'
  get 'get_applications', to: 'applies#getApplications', as: 'get_applications'
  get ':user_id', to: 'index#show', as: 'index'
  get '/events/:id/uploadImg', to:'events#uploadImg'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
    has_many_attached :images
    has_many :participants
    has_many :users, through: :participants

    has_many :pictures
    has_many :videos

    has_many :posts

    has_many :applications
    has_many :applicants, through: :applications, class_name: "User"

    scope :with_roles, -> (roles) {
        joins(:participants).merge(roles)
    }
    scope :with_organizers, -> { with_roles(Participant.organizer) }
    scope :with_co_organizers, -> { with_roles(Participant.co_organizer) }
    scope :with_audience, -> { with_roles(Participant.audience) }
    scope :with_visitors, -> { with_roles(Participant.visitor) }
    
    scope :filter_by_price, -> (prices) {where("price > ? AND price <= ?", prices[0], prices[1])}

    def self.order_list(sort_order)
        if sort_order == "price down"
            order(price: :desc)
        elsif sort_order == "price up"
            order(price: :asc)
        elsif sort_order == "newest"
            order(time: :desc)
        else
            order(time: :asc)
        end
    end

    def add_user(applicant)
        Participant.create(user: applicant, event_id: id, role: :audience)
    end

    paginates_per 24
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    skip_before_action :authorized, only: [:index]
    def index
        @events = Event.all
        if params[:title]
            @events = @events.where("title LIKE ?", "%#{params[:title]}%")
        end

        @events = sort(@events)

        @events = filter(@events)

        @events = @events.page(params[:page])
    end

    def sort(events)
        if params[:sort_by]
            events.order_list(params[:sort_by])
        else
            events
        end
    end

    def filter(events)
        if params[:filt_by]
            if params[:filt_by] == "more than 1000"
                events.where("price > ?", 1000)
            else
                conditions = params[:filt_by].split("-")
                events.filter_by_price(conditions)
            end
        else
            events
        end
    end
    
    def new
        @url = "/events"
        @method = "post"
        @event = Event.new
        @pictures = []
        @title = "New Event"
    end

    def create
        @event = Event.new(event_params)
        if @event.save
            flash[:success] = "Event created successfully"
        else
            flash[:danger]  = "Some problem occours, event was not created"
        end
        Participant.create(user_id:session[:current_user_id], event_id:@event.id, role: :organizer)
        redirect_to "/events"
    end

    def edit
        authorized_to_edit(params[:id])
        @url = "/events/#{params[:id]}"
        @method = "patch"
        @title = "Edit Event"
        @event = Event.find(params[:id])
    end

    def uploadImg
        @title = "Images"
        @event = Event.find(params[:id])
        @pictures = @event.images
    end

    def update
        authorized_to_edit(params[:id])
        e = Event.find(params[:id])
        if e.nil?
            flash[:danger]  = "No such event"
        else
            e.update(event_params)
            flash[:success]  = "Event updated"
        end
        redirect_to event_path(params[:id])
    end

    def show
        @event = Event.find(params[:id])
        @pictures = @event.images
        @count = 0
        participant_relation = @event.participants.where(user_id:session[:current_user_id])
        @canApply = !is_expired_event(@event) && (participant_relation.empty? || participant_relation.first.role == "visitor" || participant_relation.first.role == "audience")
        @apply = @event.applications.where(user_id:session[:current_user_id])
        @apply = @apply.empty? ? nil : @apply.first
        @isBooked = !participant_relation.empty? && participant_relation.first.role == "audience"
        @liked = !participant_relation.empty? && (participant_relation.first.role == "visitor" || participant_relation.last.role == "visitor")
    end

    def like
        participant_relation = Participant.where(user_id:session[:current_user_id], event_id:params[:event_id])
        if !participant_relation.empty?
            flash[:danger] = "You have already booked this event"
        else
            Participant.create(user_id:session[:current_user_id], event_id:params[:event_id], role: :visitor)
            flash[:success] = "success!"
        end
        redirect_to "/events/#{params[:id]}"
    end

    def dislike
        participant_relation = Participant.where(user_id:session[:current_user_id], event_id:params[:event_id], role: :visitor)
        if participant_relation.empty?
            flash[:danger] = "You have not yet like this event"
        else
            participant_relation.each { |p|
                p.destroy
            }
            flash[:success] = "success!"
        end
        redirect_to "/events/#{params[:event_id]}"
    end

    def add_img
        # authorized_to_edit(params[:id])
        if params[:event].nil?
            flash[:danger] = "You need to choose a file"
        else
            p = Picture.create(event_id:params[:id])
            p.update(params.require(:event).permit(:picture))
            flash[:success] = "Image uploaded"
        end
        redirect_to "/events/#{params[:id]}/uploadImg"
    end

    def delete_img
        p = Picture.find(params[:p_id])
        if p.nil?
            flash[:danger] = "No such picture"
        else
            flash[:success] = "Picture removed"
            p.destroy
        end
        redirect_to "/events/#{params[:id]}/edit"
    end

    # def book
    #     role = Participant.where(user_id:session[:current_user_id], event_id:params[:event_id]).first
    #     if !is_expired_event(Event.find(params[:event_id])) && (role.nil? || role.role == "visitor")
    #         if Participant.create(user_id:session[:current_user_id], event_id:params[:event_id], role: :audience)
    #             if !role.nil?
    #                 role.destroy
    #             end
    #             flash[:success] = "Thank you. You have successfully applied to book this event!"
    #         else
    #             flash[:danger] = "Some problem occoured while trying to apply booking"
    #         end
    #     else
    #         flash[:danger] = "You cannot book that event"
    #     end
    #     redirect_to "/events/#{params[:event_id]}"
    # end

    # def cancel
    #     p = Participant.find_by(user_id:session[:current_user_id], event_id:params[:event_id], role: :audience)
    #     if is_expired_event(Event.find(params[:event_id])) || p.nil?
    #         flash[:danger] = "You cannot cancel"
    #     else
    #         p.destroy
    #         flash[:success] = "You have canceled your book"
    #     end
    #     redirect_to "/events/#{params[:event_id]}"
    # end

    private

    def authorized_to_edit(e_id)
        if Participant.where(event_id:e_id, role:1).nil? || session[:current_user_id] != Participant.where(event_id:e_id, role:1).first.user_id
            flash[:danger] = "You cannot edit this page."
            redirect_to "/events/#{e_id}"
        end
    end

    def is_expired_event(event)
        return event.time < Time.now
    end

    def event_params
        params.require(:event).permit(:title, :price, :time, :place, :description, images: [])
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.erb
<div class="card">

  <div class="card-header">
    <nav class="navbar">
      <ul class="nav navbar-nav navbar-left">
        <h5><b><%=@title%></b></h5>
      </ul>
    </nav>
  </div>

  

  <%= form_tag(@url, id: "info", method: @method, style: "padding: 40px;") do %>

    <div class="form-group">
      <label>Title</label>
      <input type="text" class="form-control" name="title" id="title" value="<%=@event[:title]%>" required>
      <small class="form-text text-muted">Title of the event</small>
    </div>
    <br>

    <div class="form-group">
      <label>Time</label>
      <input type="text" class="form-control" name="time" id="time" value="<%=@event[:time]%>" required>
      <small class="form-text text-muted">Time when the event begins</small>
    </div>
    <br>

    <div class="form-group">
      <label>Place</label>
      <input type="text" class="form-control" name="place" id="place" value="<%=@event[:place]%>" required>
      <small class="form-text text-muted">Place of the event</small>
    </div>
    <br>

    <div class="form-group">
      <label>Price</label>
      <input type="text" class="form-control" name="price" id="price" value="<%=@event[:price]%>">
      <small class="form-text text-muted">[Optional] Price of the event ticket</small>
    </div>
    <br>

    <div class="form-group">
      <label>Description</label>
      <textarea class="form-control" name="description" id="description" required><%=@event[:description]%></textarea>
      <small class="form-text text-muted">Event description</small>
    </div>

  <% end %>

  <div style="padding: 40px;">
    <% if @title == "Edit Event" %>
      <%= render 'image_upload' %>
    <% end %>
  <button type="submit" form="info" class="btn btn-primary">Submit</button>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="add_img" tabindex="-1" role="dialog" aria-labelledby="add_img_label" aria-hidden="true">
<div class="modal-dialog" role="document">
    <%= form_for( @event, method: "post", url: "/events/picture/upload/#{@event[:id]}" ) do |f| %>
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="add_img_label">Edit Profile</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <%= f.file_field :picture %>
        </div>
        <div class="modal-footer">
            <div class="form-group row">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                 &nbsp; &nbsp;
                <%= f.submit "Save", class: "btn btn-primary" %>
            </div>
        </div>
        </div>
    <% end %>
</div>
</div>

app/views/events/_edit_form.html.erb
<div class="card">

  <div class="card-header">
    <nav class="navbar">
      <ul class="nav navbar-nav navbar-left">
        <h5><b><%=@title%></b></h5>
      </ul>
    </nav>
  </div>

  

  <%= form_for(@event, :html => { id: "info", method: @method, style: "padding: 40px;" } ) do |f| %>

    <div class="form-group">
      <label>Title</label>
      <br>
      <%= f.text_field :title%>
      <small class="form-text text-muted">Title of the event</small>
    </div>
    <br>

    <div class="form-group">
      <label>Time</label>
      <br>
      <%= f.date_field :time, :required => true%>
      <small class="form-text text-muted">Select the time when the event begins</small>
    </div>
    <br>

    <div class="form-group">
      <label>Place</label>
      <br>
      <%= f.text_field :place, id:"place" %>
      <script>
        function initAutocomplete() {
          // Create the autocomplete object, restricting the search predictions to
          // geographical location types.
          autocomplete = new google.maps.places.Autocomplete(
              document.getElementById('place'), {types: ['geocode']});

          // Avoid paying for data that you don't need by restricting the set of
          // place fields that are returned to just the address components.
          autocomplete.setFields(['address_component']);

          // When the user selects an address from the drop-down, populate the
          // address fields in the form.
          autocomplete.addListener('place_changed', fillInAddress);
        }
      </script>
      <small class="form-text text-muted">Place of the event</small>
    </div>
    <br>

    <div class="form-group">
      <label>Price</label>
      <br>
      <%= f.text_field :price%>
      <small class="form-text text-muted">[Optional] Price of the event ticket</small>
    </div>
    <br>

    <div class="form-group">
      <label>Description</label>
      <br>
      <%= f.text_area(:description, size: '50x10') %>
      <small class="form-text text-muted">Event description</small>
    </div>

      <div class="form-group">
        <label>Images</label>
        <br>
        <%= f.file_field :images, multiple: true %>
        <small class="form-text text-muted">Event posters</small>
      </div>
  <% end %>

  <div class="row" style="margin-left: 20px; margin-bottom: 20px;">
    <button type="submit" form="info" class="btn btn-primary">Submit</button>
    &nbsp;&nbsp;
    <%= button_to "/events/#{@event[:id]}", class:"btn btn-secondary", method: :get do %>
        Back
    <% end %>
  </div>
  
</div>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJW4jsPlNKgv6jFm3B5Edp5ywgdqLWdmc&&libraries=places&callback=initAutocomplete&language=en" async defer></script>

app/views/events/_events.html.erb
<% @events.each do |event| %>    
    <div class="images">
        <% if event.images.empty? %>
            <%= image_pack_tag("poster#{event[:id] % 30}.jpg") %>
        <% else %>
            <%= image_tag(event.images[0]) %>
        <% end %>
        <div class="event-info">
            <h4><%= event[:title] %></h4>
            <p><%= event[:time] %></p>
            <p><%= event[:price] %></p>
            <%= button_to "/events/#{event[:id]}", method: :get do %>
                View
            <% end %>
        </div>
    </div>
<% end %>

app/views/events/_gmap.html.erb
<head>
  <script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJW4jsPlNKgv6jFm3B5Edp5ywgdqLWdmc&sensor=false">
  </script>

  <script>
    function initialize() {
      var geocoder = new google.maps.Geocoder();
      var loc = {lat: -23.7339834, lng: 133.8694412};
      var mapProp = {
        center:loc,
        zoom:16,
        mapTypeId:google.maps.MapTypeId.ROADMAP
        };
      var map=new google.maps.Map(document.getElementById("googleMap"), mapProp);
      // bounds  = new google.maps.LatLngBounds();
      // var marker = new google.maps.Marker({position: loc, map: map});
      // bounds.extend(loc);
      // map.panToBounds(bounds);
      var address = document.getElementById('place').value;
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          });
        } 
        // else {
        //   alert('Geocode was not successful for the following reason: ' + status);
        // }
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
  </script>
</head>

app/views/events/_image_show.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <% if @pictures.length > 1 %>
    <ol class="carousel-indicators">
      <% @pictures.each { |p| %>
          <li data-target="#carouselExampleIndicators" data-slide-to=<%@count%> 
              <% if @count == 0 %>
                  class="active"
              <% end%>
          ></li>
          <% @count += 1 %>
      <% } %>
      <% @count = 0 %>
    </ol>
  <% end %>
  <div class="carousel-inner">
    <% @pictures.each { |p| %>
        <div class="carousel-item 
            <% if @count == 0 %>
                active
            <% end %>
        ">
            <%=image_tag(p, alt: "image", class: "d-block img-fluid")%>
            <% @count += 1 %>
        </div>
    <% } %>
  </div>
  <% if @pictures.length > 1 %>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>

app/views/events/_image_upload.erb
<label>Images</label>
<div class="card">
    <div class="card-body">
    <div class="row">
        <% @pictures.each { |p| %>
        <div class="image col-sm-4">
            <%=image_tag(p.picture.url, alt: "image", class: "gravatar")%>
            <div class="mask-middle">
            <%= button_to "/events/picture/delete/#{@event[:id]}/#{p[:id]}", method: :post, class:"btn btn-primary" do %>
                Remove
            <% end %>  
            </div>
        </div>
        <% } %>
    </div>
    <br><br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_img">Upload image</button>
    </div>
</div>
<br><br>

app/views/events/_search.html.erb
<%= form_for "", url: events_path, role: "search", method: :get do %>
  <%= text_field_tag :title, @search_term, placeholder: "Search ..."%>
  <%= submit_tag("Search") %>
<% end %>

app/views/events/_sortTab.html.erb
<div class="btn-group">
  <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort by
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href=<%= events_path(sort_by: "price up", filt_by: params[:filt_by]) %> >price up</a>
    <a class="dropdown-item" href=<%= events_path(sort_by: "price down", filt_by: params[:filt_by]) %>>price down</a>
    <a class="dropdown-item" href=<%= events_path(sort_by: "newest", filt_by: params[:filt_by]) %>>newest</a>
    <a class="dropdown-item" href=<%= events_path(sort_by: "oldest", filt_by: params[:filt_by]) %>>oldest</a>
  </div>
</div>

app/views/events/edit.erb
<%= render 'edit_form' %>

app/views/events/edit.html.erb
<%= render 'edit_form' %>

app/views/events/index.html.erb
<header role="banner">
    <%= image_pack_tag("gallery.png", id: "logo-main", width: "200", alt: "Logo Thing main logo") %>
    <nav class="navbar navbar-expand-sm navbar-light btn-secondary">
    <div class="container">
        <div class="collape navbar-collapse">
            <ul class="navbar-nav">
                <li>
                    <%= button_to "/events/new", method: :get, class:"btn btn-secondary" do %>
                        <%= octicon "plus", size: "80x80", style: "padding:0;margin:0" %>
                    <% end %>
                </li>
                <li><%= render 'sortTab' %></li>
                <li><%= render 'filter' %></li>
            </ul>
        </div>
        <ul class="navbar-nav navbar-right">
            <li><%= render 'search' %></li>
        </ul>
    </div>
    </nav>
</header>
<% if @events.empty? %>
    <br><h6>There is no event yet. Follow other users to see their new events by searching with the name. Or write your own events!</h6>
<% else %>
    <div class="gallery">
        <%= render :partial => 'events', :object => @events %>
        <br>
    </div>
    <p class="pagination">
        <%= link_to_next_page(@events, 'Next Page', :remote => true) %>
    </p>   
<% end %>
<%= javascript_pack_tag 'events' %>

app/views/events/new.html.erb
<%= render 'edit_form' %>

app/views/events/show.html.erb
<div class="card" style="padding-bottom: 15px;">
  <div class="card-body">
    <div class="row justify-content-center detail">
      <div class="col-md-6 align-self-center">
        <% if !@pictures.empty? %>
          <%= render 'image_show' %>
        <% else %>
        <%=image_pack_tag("no_image.jpg", class: "img-fluid", style: "padding:0;margin:0")%>
        <% end %>
      </div>
      <div class="col-md-6 align-self-center">
        <div class="row">
          <% if @event.time > Time.now %>
            <h6 class="p-2 rounded-pill bg-success text-light">
              <%= octicon "flame" %> Active
            </h6>
          <% else %>
            <h6 class="p-2 rounded-pill bg-secondary text-light">
              <%= octicon "clock" %> End
            </h6> 
          <% end %>
          <h4 class="card-title" style="padding-left: 10px; padding-top: 3px;">
            <%=@event["title"] %>
          </h4>
          
          <div style="margin-left: auto; margin-right: 20px;">
            <% if !(Participant.where(event_id:@event[:id], role:1).empty?) && session[:current_user_id] == Participant.where(event_id:@event[:id], role:1).first.user_id %>
              <div class="row">
                <%= button_to "/events/#{@event["id"]}/edit", method: :get, class:"btn btn-primary" do %>
                  Edit
                <% end %>
              </div>
            <% else %>
              <% if @liked %>
                <%= link_to "/events/#{@event["id"]}/dislike?" + {event_id: @event.id}.to_param, method: :post do %>
                  <%= octicon "star", height:32, class:"octicon" %>
                <% end %>
              <% else %>
                <%= link_to "/events/#{@event["id"]}/like?" + {event_id: @event.id}.to_param, method: :post do %>
                  <%= octicon "star", height:32, class:"octicon close" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <h6 class="card-subtitle text-muted" style="padding-top: 15px;">
          Time: <%=@event.time%>
        </h6>
        <h6 class="card-subtitle text-muted" style="padding-top: 15px;">
          Place: <%=@event.place%>
          <input id="place" value="<%=@event.place%>" hidden>
        </h6>
        <h6 class="card-subtitle text-muted" style="padding-top: 15px;">
          Price: $<%=@event.price%>
        </h6>
        <div style="padding-top: 20px;">
          <%=render 'gmap'%>
          <div id="googleMap" style="width:360px;height:250px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card" style="padding: 30px;">
  <div class="row" style="padding-left: 15px; padding-right: 15px;">
    <h4 class="card-title">
      Description
    </h4>
    <% if @canApply %>
      <div style="margin-left: auto; margin-right: 0;">
        <% if @isBooked %>
          <button class="btn btn-success disabled" style="cursor: default;">You have booked this event</button>
        <% elsif !@apply.nil? %>
          <%= button_to edit_apply_path(id:@apply["id"], event_id:@event["id"], user_id:session[:current_user_id]), method: :delete, class:"btn btn-danger"  do %>
            Cancel my application
          <% end %>
        <% else %>
          <%= button_to edit_apply_index_path(event_id:@event["id"], user_id:session[:current_user_id]), method: :post, class:"btn btn-primary"  do %>
            Apply this event
          <% end %>
        <% end %>
      </div>
    <% end %>
    </div>
  <h6 style="padding-top: 10px;">
    <%=@event["description"] %>
  </h6>
</div>
<br>
<div class="container" style="max-width:1000px">
<section id="forum">
  <h2 class="title">Forum</h2>
  <%= render_async get_forum_path(event_id: @event.id), 'data-turbolinks-track': 'reload' %>
  <%= render partial: "posts/new_modal" %>
</section>
</div>

app/views/events/uploadImg.html.erb
<div style="padding: 40px;">
    <div class="card">
        <div class="card-header">
            <nav class="navbar">
                <ul class="nav navbar-nav navbar-left">
                    <h5><b><%=@title%></b></h5>
                </ul>
            </nav>
        </div>
        <div class="card-body">
        <div class="row">
            <% @pictures.each { |p| %>
            <div class="image col-sm-4">
                <%=image_tag(p.picture.url, alt: "image", class: "gravatar")%>
                <div class="mask-middle">
                <%= button_to "/events/picture/delete/#{@event[:id]}/#{p[:id]}", method: :post, class:"btn btn-primary" do %>
                    Remove
                <% end %>  
                </div>
            </div>
            <% } %>
        </div>
        <br><br>
            <div class="row">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add_img">Upload image</button>
                &nbsp;&nbsp;
                <%= button_to "/events/#{@event[:id]}", class:"btn btn-secondary", method: :get do %>
                    Back
                <% end %>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="add_img" tabindex="-1" role="dialog" aria-labelledby="add_img_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
      <%= form_for( @event, method: "post", url: "/events/picture/upload/#{@event[:id]}" ) do |f| %>
          <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="add_img_label">Edit Profile</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <%= f.file_field :picture %>
          </div>
          <div class="modal-footer">
              <div class="form-group row">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  &nbsp; &nbsp;
                  <%= f.submit "Save", class: "btn btn-primary" %>
              </div>
          </div>
          </div>
      <% end %>
  </div>
</div>