config/routes.rb
Rails.application.routes.draw do
  get 'get_follows', to: 'follows#getFollows'
  get 'user_search', to: 'follows#userSearch'
  root 'index#home'
  get 'sign_out', to: 'session#destroy'
  get 'auth/:provider/callback', to: 'session#googleAuth'
  get 'auth/failure', to: redirect('/')
  get 'sign_in', to: 'session#new'
  post 'log_in', to: 'session#create'
  patch 'users/:id/update_portrait', to: 'users#updatePortrait', as: 'update_portrait'
  patch 'users/:id/update_pwd', to: 'users#updatePassword', as: 'update_pwd'
  get 'profile', to: 'profile#show'
  get 'api/get_events', to: 'api#getEvents', as: 'get_events'
  post 'events/:id/like', to: 'events#like', as: 'like_event'
  post 'events/:id/dislike', to: 'events#dislike', as: 'dislike_event'
  # post 'events/book', to: 'events#book', as: 'book_event'
  # post 'events/cancel', to: 'events#cancel', as: 'cancel_event'
  post 'events/picture/upload/:id', to: 'events#add_img'
  post 'events/picture/delete/:id/:p_id', to: 'events#delete_img'
  get 'get_forum', to: 'posts#getForum', as: 'get_forum'
  resources :users
  resources :events
  resources :posts
  resources :applies, path: :applications, only: [:create, :destroy], as: "edit_apply"
  post 'follows', to: 'follows#create'
  delete 'follows', to: 'follows#destroy'
  post 'applications/:id/approve', to: 'applies#approve', as: 'application_approve'
  post 'applications/:id/disapprove', to: 'applies#disapprove', as: 'application_disapprove'
  get 'get_applications', to: 'applies#getApplications', as: 'get_applications'
  get ':user_id', to: 'index#show', as: 'index'
  get '/events/:id/uploadImg', to:'events#uploadImg'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :event
  belongs_to :author, class_name: "User", foreign_key: "user_id"
  
  belongs_to :parent, class_name: "Post", optional: true

  has_many :replies, class_name: "Post", foreign_key: "parent_id"

  scope :with_roots, -> {
    where(parent: nil)
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :correct_user, only: [:update, :destroy]

    def getForum
        @posts = Post.where(event_id: params[:event_id]).with_roots
        @event = Event.where(event_id: params[:event_id])
        render partial: "posts", object: @posts, locals: {depth: 0, id: ''}
    end

    def new
        @post = Post.new
        @post.event_id = params[:event_id]
        @post.user_id = params[:user_id]
        @post.parent_id = params[:parent_id]
        @post.title = "Re: " + Post.find(params[:parent_id]).title
    end

    def create
        if params[:commit] == 'Post'
            @post = Post.new(post_params)
            if @post.save
                flash[:success] = "Post successfully"
                redirect_to event_path(id: post_params[:event_id])
            else
                render 'new'
            end
        else
            redirect_to event_path(id: post_params[:event_id])
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        if params[:commit] == 'Save'
            if @post.update(post_params)
                flash[:success] = "Edit successfully"
                redirect_to event_path(id: @post.event_id)
            else
                render 'new'
            end
        else
            redirect_to event_path(id: @post.event_id)
        end
    end

    def destroy
        event_id = @post.event_id
        @post.destroy
        flash[:success] = "Post deleted"
        redirect_to event_path(id: event_id)
    end

    private

    def post_params
        params.require(:post).permit(:event_id, :user_id, :parent_id,
                                     :title, :content)
    end

    def correct_user
        @post = current_user.posts.find_by(id: params[:id])
        redirect_to root_url if @post.nil?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit.html.erb
<div class="card-footer">
<%= form_for( @post , method: "patch", remote: true) do |f| %>
  <div class="form-group row">
    <%= f.label :title, class: "col-form-label col-sm-2" %>
    <%= f.text_field :title, class: "col-sm-9" %>
  </div>
  <div class="form-group row">
    <%= f.label :content, class: "col-form-label  col-sm-2" %>
    <%= f.text_area :content, class:" col-sm-9 form-control" %>
  </div>
  <div class="form-group justify-content-end row">
    <%= f.submit "Save", class: "btn btn-primary" %>
     &nbsp &nbsp
    <%= f.submit "Cancel", class: "btn btn-danger" %>
    <div class="col-1"></div>
  </div>
<% end %>
</div>

app/views/posts/_new.html.erb
<div class="card-footer">
<%= form_for( @post , remote: true) do |f| %>
  <div class="form-group justify-content-end row">
    <%= f.label :content, class: "col-form-label col-sm-2" %>
    <%= f.text_area :content, class:"form-control col" %>
    <div class="col-1"></div>
    
  </div>
  <%= f.hidden_field :event_id %>
  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :parent_id %>
  <%= f.hidden_field :title %>
  <div class="form-group justify-content-end row">
    <%= f.submit "Post", class: "btn btn-primary" %>
    &nbsp &nbsp
    <%= f.submit "Cancel", class: "btn btn-danger" %>
    <div class="col-1"></div>
  </div>
<% end %>
</div>

app/views/posts/_new_modal.html.erb
<br>
<div class="row justify-content-center">
    <button type="button" class="btn btn-success col-4" data-toggle="modal" data-target="#new_post">New</button>
</div>
<!-- Modal -->
<div class="modal fade" id="new_post" tabindex="-1" role="dialog" aria-labelledby="new_post_label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <%= form_for( :post, url: '/posts', remote: true ) do |f| %>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="new_post_label">Edit post</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <%= f.label :title, class: "col-form-label col-sm-2" %>
                        <%= f.text_field :title, class: "col-sm-8" %>
                    </div>
                    <div class="form-group row">
                        <%= f.label :content, class: "col-form-label  col-sm-2" %>
                        <%= f.text_area :content, class:" col-sm-8 form-control" %>
                    </div>
                    <%= f.hidden_field :event_id, value: @event.id %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                </div>
                <div class="modal-footer">
                    <div class="form-group text-right">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        &nbsp &nbsp
                        <%= f.submit "Post", class: "btn btn-primary" %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/posts/_posts.html.erb
<% posts.each_with_index do |post, i| %>
  <% user = post.author %>
  <% new_id = depth == 0 ? i.to_s : id + '-' + i.to_s %>
  <% if depth == 0 %>
  <div class="row root">
  <% else %>
  <div class="row reply">
  <% end %>
    <div class=<%= "col-" + depth.to_s %>></div>
    <div class="col">
      <div class="card" id=<%= new_id %>>
        <div class="card-header post-header">
          <%= gravatar_for(user) %>
          <div class="post-header-text">
            <b><%= "Re: " if depth != 0 %> <%= post.title %></b>
            <br>
            By <%= user.name %> - <%= post.updated_at %>
          </div>
        </div>
        <div class="card-body">
          <p class="card-text"><%= post.content %></p>
          <div class="text-right">
            <% if current_user?(post.author) %>
              <%= link_to  "delete", post, controller: 'posts', method: 'delete', data: {confirm: "You sure"} %> &nbsp &nbsp
              <%= link_to  "edit", edit_post_path(id: post.id, ix: new_id, event_id: post.event_id), remote: true %> &nbsp &nbsp
            <% end %>
            <%= link_to  "reply", new_post_path(event_id: post.event_id, user_id: current_user.id, parent_id: post.id, ix: new_id), remote: true %>
          </div>
        </div>
        <div class="post-form"></div>
      </div>
    </div>
  </div>
  <%= render partial: "posts", object: post.replies, as: :posts, locals: {depth: depth + 1, id: new_id} %>
<% end %>

app/views/posts/edit.js.erb
$('#<%= params[:ix] %> .post-form').html("<%= j( render :partial => 'edit' ) %>")

app/views/posts/new.js.erb
$('#<%= params[:ix] %> .post-form').html("<%= j( render :partial => 'new' ) %>")